version: '3.8'
services:
  app:
    container_name: social-network-prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: npm start

  db:
    container_name: postgres-db-prod
