version: '3.8'
services:
  app:
    restart: on-failure
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - DB_HOST=db
    depends_on:
      - db
  db:
    container_name: postgres-db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
